version: "3.9"

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: app-php
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - app-php

  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-php

networks:
  app-php:
    driver: bridge